-- Apply through the generated migration. Service-only writes; authorized admins read.
create table public.vehicle_queries(id uuid primary key default gen_random_uuid(),plate text not null,status text not null default 'CREATED',started_at timestamptz,completed_at timestamptz,latency_ms integer,total_data_cost_pen numeric(12,4) not null default 0,created_at timestamptz not null default now());
create table public.vehicles(id uuid primary key default gen_random_uuid(),plate text unique not null,vin text,brand text,model text,manufacture_year integer,model_year integer,color text,engine text,canonical_json jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.provider_calls(id uuid primary key default gen_random_uuid(),query_id uuid references public.vehicle_queries,provider text not null,endpoint text not null,request_fingerprint text not null,status text not null,http_status integer,latency_ms integer,cost_pen numeric(12,4) not null default 0,coverage_json jsonb,error_code text,created_at timestamptz not null default now());
create table public.provider_evidence(id uuid primary key default gen_random_uuid(),query_id uuid references public.vehicle_queries,field_path text not null,value_json jsonb,provider text not null,original_source text,status text not null,checked_at timestamptz not null,freshness_expires_at timestamptz not null,metadata_json jsonb);
create table public.vehicle_snapshots(id uuid primary key default gen_random_uuid(),vehicle_id uuid references public.vehicles,query_id uuid unique references public.vehicle_queries,snapshot_json jsonb not null,created_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),plate text not null,email text not null,phone text not null,amount_pen numeric(10,2) not null check(amount_pen>0),payment_method text not null check(payment_method in ('YAPE','PLIN')),payment_reference text,payment_proof_path text,status text not null default 'PAYMENT_PENDING' check(status in ('PAYMENT_PENDING','PAYMENT_REVIEW','PAID','REJECTED','REPORT_PROCESSING','REPORT_READY','REPORT_PARTIAL','FAILED')),created_at timestamptz not null default now(),paid_at timestamptz,approved_by uuid references auth.users,access_token_hash text not null,failure_code text,processing_started_at timestamptz);
create table public.reports(id uuid primary key default gen_random_uuid(),order_id uuid unique not null references public.orders,vehicle_id uuid references public.vehicles,query_id uuid unique references public.vehicle_queries,public_code text unique not null,report_json jsonb not null,summary_json jsonb,status text not null,pdf_path text,total_data_cost_pen numeric(12,4) not null default 0,email_status text not null default 'PENDING',created_at timestamptz not null default now(),expires_at timestamptz);
create table public.preview_rate_limits(ip_hash text not null,hour_bucket timestamptz not null,count integer not null,primary key(ip_hash,hour_bucket));
create table public.preview_cache(plate text primary key,data jsonb not null,expires_at timestamptz not null);
create index on public.orders(status,created_at desc);create index on public.provider_calls(query_id);create index on public.provider_evidence(query_id);create index on public.reports(created_at desc);create index on public.vehicle_queries(plate,created_at desc);
create view public.provider_health_daily with (security_invoker=true) as select date_trunc('day',created_at) as day,provider,count(*) as calls,count(*) filter(where status='VERIFIED') as success_count,count(*) filter(where status='UNAVAILABLE') as failure_count,avg(latency_ms) as avg_latency_ms,count(*) filter(where status='NOT_FOUND') as empty_count,count(*) filter(where status='CONFLICT') as conflict_count,sum(cost_pen) as estimated_cost_pen from public.provider_calls group by 1,2;
do $$ declare t text;begin foreach t in array array['vehicle_queries','vehicles','provider_calls','provider_evidence','vehicle_snapshots','orders','reports','preview_rate_limits','preview_cache'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon, authenticated',t);execute format('grant select on public.%I to authenticated',t);execute format('grant all on public.%I to service_role',t);execute format('create policy admin_read on public.%I for select to authenticated using ((select auth.jwt())->''app_metadata''->>''role'' = ''admin'')',t);end loop;end $$;
grant select on public.provider_health_daily to authenticated,service_role;revoke all on public.provider_health_daily from anon;
create function public.consume_rate_limit(p_hash text,p_limit integer) returns boolean language plpgsql security invoker set search_path='' as $$ declare n integer;begin insert into public.preview_rate_limits values(p_hash,date_trunc('hour',now()),1) on conflict(ip_hash,hour_bucket) do update set count=public.preview_rate_limits.count+1 returning count into n;return n<=p_limit;end $$;
create function public.approve_order(p_id uuid,p_admin uuid) returns boolean language plpgsql security invoker set search_path='' as $$ declare n integer;begin update public.orders set status='PAID',paid_at=now(),approved_by=p_admin where id=p_id and status='PAYMENT_REVIEW' and payment_proof_path is not null;get diagnostics n=row_count;return n=1;end $$;
create function public.claim_report(p_id uuid) returns boolean language plpgsql security invoker set search_path='' as $$ declare n integer;begin update public.orders set status='REPORT_PROCESSING',processing_started_at=now() where id=p_id and status='PAID';get diagnostics n=row_count;return n=1;end $$;
create function public.commit_report(p_order uuid,p_query uuid,p_code text,p_report jsonb,p_summary jsonb,p_cost numeric,p_status text) returns uuid language plpgsql security invoker set search_path='' as $$ declare v uuid;r uuid;begin
if not exists(select 1 from public.orders where id=p_order and status='REPORT_PROCESSING' for update) then raise exception 'INVALID_STATE';end if;
insert into public.vehicles(plate,vin,brand,model,manufacture_year,model_year,color,engine,canonical_json) values(p_report#>>'{identity,plate}',p_report#>>'{identity,vin}',p_report#>>'{identity,brand}',p_report#>>'{identity,model}',nullif(p_report#>>'{identity,manufactureYear}','')::integer,nullif(p_report#>>'{identity,modelYear}','')::integer,p_report#>>'{identity,color}',p_report#>>'{identity,engine}',p_report) on conflict(plate) do update set canonical_json=excluded.canonical_json,vin=excluded.vin,brand=excluded.brand,model=excluded.model,manufacture_year=excluded.manufacture_year,model_year=excluded.model_year,color=excluded.color,engine=excluded.engine,updated_at=now() returning id into v;
insert into public.reports(order_id,vehicle_id,query_id,public_code,report_json,summary_json,total_data_cost_pen,status) values(p_order,v,p_query,p_code,p_report,p_summary,p_cost,p_status) returning id into r;
insert into public.vehicle_snapshots(vehicle_id,query_id,snapshot_json) values(v,p_query,p_report);
update public.orders set status=p_status where id=p_order;
update public.vehicle_queries set status=case when p_status='REPORT_READY' then 'COMPLETED' else 'PARTIAL' end,completed_at=now(),total_data_cost_pen=p_cost,latency_ms=extract(epoch from (now()-started_at))*1000 where id=p_query;return r;end $$;
revoke execute on function public.consume_rate_limit(text,integer),public.approve_order(uuid,uuid),public.claim_report(uuid),public.commit_report(uuid,uuid,text,jsonb,jsonb,numeric,text) from public,anon,authenticated;
grant execute on function public.consume_rate_limit(text,integer),public.approve_order(uuid,uuid),public.claim_report(uuid),public.commit_report(uuid,uuid,text,jsonb,jsonb,numeric,text) to service_role;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('payment-proofs','payment-proofs',false,5242880,array['image/jpeg','image/png','image/webp']),('report-pdfs','report-pdfs',false,10485760,array['application/pdf']) on conflict(id) do nothing;

create function public.admin_metrics() returns jsonb language sql security invoker set search_path='' as $$ select jsonb_build_object('pending',(select count(*) from public.orders where status='PAYMENT_REVIEW'),'reports_today',(select count(*) from public.reports where (created_at at time zone 'America/Lima')::date=(now() at time zone 'America/Lima')::date),'revenue',(select coalesce(sum(amount_pen),0) from public.orders where paid_at is not null),'cost',(select coalesce(sum(cost_pen),0) from public.provider_calls),'average_cost',(select coalesce(avg(total_data_cost_pen),0) from public.reports)); $$;
revoke execute on function public.admin_metrics() from public,anon,authenticated;grant execute on function public.admin_metrics() to service_role;
